name: gallery_saver_example
description: Demonstrates how to use the gallery_saver plugin.
publish_to: "none"

environment:
  sdk: ^3.8.1

dependencies:
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.5.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  gallery_saver:
    path: ../

flutter:
  uses-material-design: true
